language: generic

dist: trusty

services:
  - docker

matrix:
  include:
    - env: DOCKER_IMAGE="cxx"
    - env: DOCKER_IMAGE="qt"
    - env: DOCKER_IMAGE="java"
    - env: DOCKER_IMAGE="android"
    - env: DOCKER_IMAGE="latex"

script:
  - cd $DOCKER_IMAGE
  - docker build -t lamtev/$DOCKER_IMAGE . 
