language: generic

dist: trusty

services:
  - docker

matrix:
  include:
    - env: DOCKER_IMAGE="cxx-build-tools"
    - env: DOCKER_IMAGE="qt-build-tools"
    - env: DOCKER_IMAGE="java-build-tools"
    - env: DOCKER_IMAGE="android-build-tools"
    - env: DOCKER_IMAGE="latex-build-tools"

script:
  - cd $DOCKER_IMAGE
  - docker build -t lamtev/$DOCKER_IMAGE . 
