language: generic

services:
  - docker

script:
  - cd cxx-build-tools
  - docker build -t lamtev/cxx-build-tools . 
  - cd ..
    
  - cd latex-build-tools
  - docker build -t lamtev/latex-build-tools . 
  
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then	
      
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";		
      docker tag lamtev/cxx-build-tools lamtev/cxx-build-tools:$(date +%Y%m%d%H%M%S);		
      docker push lamtev/cxx-build-tools;
    
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";		
      docker tag lamtev/latex-build-tools lamtev/latex-build-tools:$(date +%Y%m%d%H%M%S);		
      docker push lamtev/latex-build-tools;
      
    fi
