language: generic

dist: trusty

services:
  - docker

matrix:
  include:
    - env: DOCKER_IMAGE="base"
    - env: DOCKER_IMAGE="cxx"
    - env: DOCKER_IMAGE="qt"
    - env: DOCKER_IMAGE="java"
    - env: DOCKER_IMAGE="android"
    - env: DOCKER_IMAGE="latex"
    - env: DOCKER_IMAGE="python"

script:
  - cd $DOCKER_IMAGE
  - chmod +x build.sh
  - ./build.sh
