sudo: required

language: generic

services:
  - docker

script:
  - docker build -t lamtev/build-tools .
  
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "pushFixing" ]; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker tag lamtev/build-tools lamtev/build-tools:$(date +%Y%m%d%H%M%S);
      docker push lamtev/build-tools;
    fi
